language: node_js
node_js:
  - '4.4'
braches:
  only:
    - master
install: npm install
after_success:
  curl -H "Content-Type: application/json" --data '{"build": true}' -X POST $DOCKER_HUB_TRIGGER_URL
